/** Site CMS keys fetched for the homepage. */
export const HOME_CMS_KEYS = [
  'landing.hero.eyebrow',
  'landing.hero.headline1',
  'landing.hero.headline2',
  'landing.hero.subtext',
  'landing.hero.cta.primary',
  'landing.hero.cta.secondary',
  'landing.hero.portrait',
  'landing.hero.bg_image',
  'landing.hero.bg_video',
  'landing.hero.bg_overlay',
  'landing.hero.bg_position',
  'landing.hero.bg_position_mobile',
  'landing.vision.label',
  'landing.vision.heading',
  'landing.vision.subheading',
  'landing.vision.text',
  'landing.vision.mission.label',
  'landing.vision.mission.heading',
  'landing.vision.mission.scripture',
  'landing.vision.activities',
  'landing.cta.headline',
  'landing.cta.subtext',
  'landing.cta.label',
  'landing.cta.button',
  'landing.cta.buttonSecondary',
  'stats.enabled',
  'stats.stat1.number',
  'stats.stat1.suffix',
  'stats.stat1.label',
  'stats.stat2.number',
  'stats.stat2.suffix',
  'stats.stat2.label',
  'stats.stat3.number',
  'stats.stat3.suffix',
  'stats.stat3.label',
  'stats.stat4.number',
  'stats.stat4.suffix',
  'stats.stat4.label',
  'shepherd.quote',
  'shepherd.name',
  'shepherd.title',
  'shepherd.portrait',
  'shepherd.image',
  'shepherd.link',
  'highlights.section.eyebrow',
  'highlights.section.title',
  'highlights.section.titleAccent',
  'highlights.1.title',
  'highlights.1.desc',
  'highlights.2.title',
  'highlights.2.desc',
  'highlights.3.title',
  'highlights.3.desc',
  'highlights.4.title',
  'highlights.4.desc',
  'confession.home.label',
  'confession.home.lines',
  'confession.home.footer',
  'confession.home.link',
  'landing.gallery.eyebrow',
  'landing.gallery.title',
  'landing.gallery.titleAccent',
  'landing.gallery.subtext',
  'landing.gallery.cta',
] as const

export const ABOUT_CMS_KEYS = [
  'about.hero.eyebrow',
  'about.hero.headline1',
  'about.hero.headline2',
  'about.vision.text',
  'about.mission.heading',
  'about.mission.scripture',
  'about.mission.text',
  'about.yadah.bio',
  'about.yadah.image',
  'about.yadah.musicLink',
  'about.activities.heading',
  'about.activities.1.title',
  'about.activities.1.desc',
  'about.activities.2.title',
  'about.activities.2.desc',
  'about.activities.3.title',
  'about.activities.3.desc',
  'about.activities.4.title',
  'about.activities.4.desc',
  'about.activities.5.title',
  'about.activities.5.desc',
  'about.activities.6.title',
  'about.activities.6.desc',
  'about.confession.heading',
  'about.confession.text',
  'about.confession.link',
  'about.shepherd.heading',
  'about.shepherd.name',
  'about.shepherd.role',
  'about.shepherd.websiteLink',
  'about.shepherd.musicLinkLabel',
  'about.cta.headline',
  'about.cta.subtext',
  'about.cta.button',
] as const

export const CONFESSION_CMS_KEYS = [
  'confession.full.lines',
  'confession.page.eyebrow',
  'confession.page.title',
  'confession.page.intro',
  'confession.page.cta.headline',
  'confession.page.cta.subtext',
  'confession.page.cta.primary',
  'confession.page.cta.secondary',
  'confession.page.footer',
] as const

export const CONTACT_CMS_KEYS = [
  'contact.eyebrow',
  'contact.heading',
  'contact.subheading',
  'contact.email',
  'contact.whatsapp',
  'contact.instagram',
  'contact.youtube',
  'contact.twitter',
  'contact.instagramHandle',
  'contact.youtubeHandle',
  'contact.twitterHandle',
  'contact.address',
  'contact.responseNote',
] as const

export const JOIN_CMS_KEYS = [
  'join.hero.line1',
  'join.hero.line2',
  'join.hero.line3',
  'join.hero.line4',
  'join.hero.line5',
] as const

export const PRAYER_CMS_KEYS = [
  'prayer.eyebrow',
  'prayer.title',
  'prayer.subtitle',
  'prayer.privacy',
] as const

export const PAGES_CMS_KEYS = [
  'pages.word.eyebrow',
  'pages.word.title',
  'pages.word.subtitle',
  'pages.study.eyebrow',
  'pages.study.title',
  'pages.study.subtitle',
  'pages.events.eyebrow',
  'pages.events.title',
  'pages.events.subtitle',
  'pages.gallery.eyebrow',
  'pages.gallery.title',
  'pages.gallery.subtitle',
  'pages.blog.eyebrow',
  'pages.blog.title',
  'pages.blog.subtitle',
  'pages.testimonies.eyebrow',
  'pages.testimonies.title',
  'pages.testimonies.subtitle',
] as const
